1.0.5

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,7 +37,11 @@ jobs:
 
       - name: Decode keystore
         run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.jks
-
+      - name: Debug keystore
+        run: |
+            ls -la release.jks
+            file release.jks
+            keytool -list -v -keystore release.jks -storepass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" || echo "keytool failed here"
       - name: Create keystore.properties
         run: |
           cat > src-tauri/gen/android/keystore.properties << EOF
